# Basic Site Settings
locale: "en-US"
site_theme: "default"
title: "Zihan (Tina) Zhang / Homepage"
title_separator: "-"
name: &name "Zihan (Tina) Zhang"
description: &description "Graduate student in Statistics | Causal Inference · Health Data · Computational Social Science"
url: "https://tinazhangzh.github.io"
baseurl: ""
repository: "tinazhangzh/tinazhangzh.github.io"

# Site Author
author:
  avatar: "profile.png"  # 确保你有上传图片到 /images/profile.png
  name: "Zihan (Tina) Zhang"
  bio: "Graduate student in Statistics at Columbia University. Passionate about causal inference, health data, and the social impact of data science."
  location: "New York, NY"
  employer: "Columbia University"
  email: "yourname@columbia.edu"  # ✅ 修改为你的邮箱

  # Academic profiles
  googlescholar: "https://scholar.google.com/citations?user=YOUR_ID"  # ✅ 换成你的 ID
  orcid: "https://orcid.org/0000-0000-0000-0000"  # 可选
  github: "tinazhangzh"
  linkedin: "your-linkedin-id"  # ✅ 如有可填

# Publication Categories
publication_category:
  books:
    title: "Books"
  manuscripts:
    title: "Journal Articles"
  conferences:
    title: "Conference Papers"

# Optional Features
teaser:  # 预览图，可留空
breadcrumbs: false
words_per_minute: 160
read_more: "disabled"
talkmap_link: false
comments:
  provider: false

# Atom Feed
atom_feed:
  hide: false

# Analytics
analytics:
  provider: false

# Markdown Settings
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# Default Layouts
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true

# Permalink & Output
permalink: /:categories/:title/
timezone: America/New_York
